### PR TITLE
Add NATS example

### PR DESCRIPTION
**Pull request by wallyqs**
Hi! Sharing an example of how to create a named connection using https://nats.io

Signed-off-by: Waldemar Quevedo <wally@synadia.com>

### CODE REVIEW

**Comment by andygrunwald** [comment]
That is pretty cool, @wallyqs.
Thanks a lot.

I never worked with nats, please allow me a question:
Is there a way to see which clients are connected on a nats server / cluster?
I was not able to find this quickly in the docs.

PS: Pretty cool that you API examples foster a connection/client name.

**Comment by wallyqs** [comment]
Yes, you can find them via the monitoring port, example demo endpoint: http://demo.nats.io:8222/connz

**Comment by andygrunwald** [comment]
That is pretty awesome.
Let me take this PR, merge it and add some context to the repository including READMEs and how to run it locally.

**Comment by andygrunwald** [comment]
Thanks @wallyqs!

**Pull request merged**
